# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: hello-world
description: The simplest possible demonstration
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.js: |-
        const { events } = require("@brigadecore/brigadier");

        events.on("github.com/brigadecore/brigade/cli", "exec", () => {
          console.log("Hello, World!");
        });
