# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.1
kind: Project
metadata:
  id: pipeline-demo
description: A project that demonstrates a simple pipeline
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.js: |-
        const { events, Job } = require("@brigadecore/brigadier");

        events.on("brigade.sh/cli", "exec", async event => {
          let fooJob = new Job("foo", "debian:latest", event);
          fooJob.primaryContainer.command = ["echo"];
          fooJob.primaryContainer.arguments = ["foo"];
          await fooJob.run();

          let barJob = new Job("bar", "debian:latest", event);
          barJob.primaryContainer.command = ["echo"];
          barJob.primaryContainer.arguments = ["bar"];
          await barJob.run();
        });

        events.process();
