# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.3
kind: Project
metadata:
  id: yarn
description: A project with third-party dependencies managed using yarn
spec:
  workerTemplate:
    logLevel: DEBUG
    configFilesDirectory: examples/08-yarn/.brigade
    git:
      cloneURL: https://github.com/brigadecore/brigade.git
      ref: refs/heads/v2
