apiVersion: brigade.io/v1
kind: Pipeline
metadata:
  name: build-my-app
spec:
  name: default-pipeline
  namespace: default
  phases:
    - name: kaniko-build
      params:
        - name: imageTag
          value: "test-build:{{Build-ID}}"
        - name: registry-secret
          value: acr-creds
    - name: deploy
      params:
        - name: image
          value:
            fromComponentRef:
              - name: kaniko-build
                value: imageTag