apiVersion: brigade.io/v1
kind: PipelineDefinition
metadata:
  name: default-pipeline
spec:
  description: "This is a sample pipeline definition"
  params:
    - name: imageTag
      kind: string
    - name: dockerFile
      kind: string
  phases:
    - name: kaniko-build
      namespace: default
      params:
        - name: imageTag
          valueFromParam: imageTag
