apiVersion: brigade.io/v1
kind: PipelineDefinition
metadata:
  name: default-pipeline
spec:
  pipeline:
    - name: kaniko-build
      mandatory: true
      kind: PipelineComponent #make this the default so it doesnt need to be specified everytime
