apiVersion: brigade.io/v1
kind: PipelineComponent
metadata:
  name: kaniko-build
spec:
  params:
    - name: dockerFile
      type: string
    - name: imageTag
      type: string
    - name: registry-secret
      type: string
  template:
    image: gcr.io/kaniko-project/executor:latest
    args:
      - --dockerfile={{dockerFile}}
      - --destination={{imageTag}}
    env:
      - name: CREDS
        value: asdf
    secrets:
      - name: "{{registry-secret}}"
