# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.1
kind: Project
metadata:
  id: hello-typescript
description: You can use TypeScript!
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.ts: |
        console.log("Hello, TypeScript!")
