apiVersion: v1
kind: Secret
metadata:
  name: brigade-{{ sha256sum .Values.project| trunc 54 }}
  labels:
    app: brigade
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
    component: project
  annotations:
    projectName: {{ .Values.project | quote }}
type: Opaque
data:
  repository: {{ .Values.repository | b64enc }}
  sharedSecret: {{ .Values.sharedSecret | b64enc }}
  cloneURL: {{ .Values.cloneURL | b64enc }}
  {{ if .Values.vcsSidecar }}
  vcsSidecar: {{ .Values.vcsSidecar | b64enc }}
  {{- end }}
  {{ if .Values.secrets }}
  secrets: {{ .Values.secrets | toJson | b64enc }}
  {{- end }}
  {{ if .Values.github.token }}
  github.token: {{.Values.github.token | b64enc }}
  {{- end }}
  {{ if .Values.sshKey }}
  sshKey: {{.Values.sshKey | replace "\n" "$" | b64enc }}
  {{- end }}
