# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.1
kind: Project
metadata:
  id: hello-world
description: The simplest possible demonstration
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.ts: |-
        import { events } from "@brigadecore/brigadier"

        events.on("brigade.sh/cli", "exec", () => {
          console.log("Hello, World!")
        })

        events.process()
