apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: hello-world
description: The simplest possible demonstration
spec:
  workerTemplate:
    logLevel: DEBUG
    defaultConfigFiles:
      brigade.ts: |-
        import { events } from "@brigadecore/brigadier"

        events.on("github.com/brigadecore/brigade/cli", "exec", () => {
          console.log("Hello, World!")
        })
