name: Brigade v2 Merge

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Windows logger agent
        run: |
          docker build -f v2/logger/Dockerfile.winserv-2019 v2/logger
