name: Brigade v2 Merge

on:
  push:
    branches:
      - v2
    tags:
      - 'v2.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows logger agent
        run: make build-logger-windows
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Windows logger agent
        run: DOCKER_REGISTRY=brigadecore make push-logger-windows